=== qm821493002/BrightWebFramework/BrightWebFrameworkDemo/src/bright-config.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.bright.com"
           xmlns="http://www.bright.com"
           elementFormDefault="qualified">
    <xs:element name="note">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="from">

                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="test1"></xs:element>
                            <xs:element name="test2"></xs:element>

                        </xs:sequence>
                        <xs:attribute name="attribute1" type="xs:string"></xs:attribute>
                    </xs:complexType>

                </xs:element>
                <xs:element name="to" type="xs:string"/>

                <xs:element name="heading" type="xs:string"/>
                <xs:element name="body" type="xs:string"/>
                <xs:element name="age" type="xs:integer"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== qm821493002/BrightWebFramework/BrightWebFrameworkDemo/out/production/BrightWebFrameworkDemo/Demo1.xml
<?xml version="1.0"?>

<note
        xmlns="http://www.bright.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.bright.com bright-config.xsd">

    <from attribute1="sd">
        <test1>sd</test1>
        <test2>sds</test2>
    </from>
    <to>Sam</to>
    <heading>Reminder</heading>
    <body>Don't forget me this weekend!</body>
    <age >18</age>

</note>
