=== qm821493002/BrightWebFramework/BrightWebFrameworkDemo/out/production/BrightWebFramework/bright-config.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.bright.cn"
           xmlns="http://www.bright.cn"
           elementFormDefault="qualified">


    <!--根节点-->
    <xs:element name="bright-config">
        <xs:complexType>
            <xs:sequence>
                <!--配置异常行为-->
                <xs:element ref="error-config" minOccurs="0" ></xs:element>
                <!--配置actor的基础扫描包-->
                <xs:element name="scann-package"  minOccurs="0" type="xs:string"></xs:element>
                <!--配置放行文件后缀名,逗号分隔-->
                <xs:element name="allclear" minOccurs="0" ></xs:element>
                <!--配置modules(有顺序)-->
                <xs:element ref="modules" minOccurs="0"></xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!--moduls配置(拦截器)-->
    <xs:element name="modules" >
        <xs:complexType>
            <xs:sequence>
                <xs:element name="module"  maxOccurs="unbounded"  type="xs:string"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!--error-config配置(配置出现异常或者 数据验证失败的行为)-->
    <xs:element name="error-config" >
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="convert-failed" minOccurs="0"  maxOccurs="1"></xs:element>
                <xs:element ref="validation-failed" minOccurs="0"  maxOccurs="1" ></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="convert-failed"  default="ADD_WARING_FIELD">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="ADD_WARING_FIELD"/>
                <xs:enumeration value="THROW_EXCEPTION"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="validation-failed"  default="ADD_WARING_FIELD" >
        <xs:simpleType>
            <xs:restriction base="xs:string" >
                <xs:enumeration value="ADD_WARING_FIELD"/>
                <xs:enumeration value="THROW_EXCEPTION"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

</xs:schema>

=== qm821493002/BrightWebFramework/BrightWebFrameworkDemo/out/production/BrightWebFramework/bright-global-config.xml
<?xml version="1.0"?>

<bright-config
        xmlns="http://www.bright.cn"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.bright.cn bright-config.xsd">
    <error-config>
        <convert-failed>ADD_WARING_FIELD</convert-failed>
        <validation-failed>ADD_WARING_FIELD</validation-failed>
    </error-config>

    <allclear>jsp,html,js,css,jpg,gif,htm,png</allclear>
    <!--定义的modul将按照顺序执行,此为默认的执行顺序-->
    <modules>
        <module>cn.bright.webframework.module.imp.ActorFinderModule</module>
        <module>cn.bright.webframework.module.imp.URIParseModule</module>
        <module>cn.bright.webframework.module.imp.ActorBuildModule</module>
        <module>cn.bright.webframework.module.imp.UpLoadModule</module>
        <module>cn.bright.webframework.module.imp.DataConvertModule</module>
        <module>cn.bright.webframework.module.imp.ValidationModule</module>
    </modules>
</bright-config>
